#!/usr/bin/env bash
# Regenerate the chime clips in public/sounds/ from pure synthesis.
#
# Everything here is generated by ffmpeg from mathematical expressions — no
# sample is downloaded, recorded, or copied from anywhere, so the whole set is
# ours to ship under the project's own terms with no attribution question.
#
# That is also the limit of it. Sibilance and struck-metal synthesise well;
# animal voices do not. `pspsps` and `bell` below are genuinely finished.
# `bark`, `meow` and `goodboy` are deliberate stand-ins so the feature is wired,
# testable and shippable-in-debug — they are NOT final, and public/sounds/README.md
# says which is which and where to get real ones.
#
# Usage: tools/gen-chimes.sh          (writes into public/sounds/)
#
# Requires: ffmpeg with libvorbis. No sox, no espeak — this machine has neither.

set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
out="$here/public/sounds"
mkdir -p "$out"

command -v ffmpeg >/dev/null || { echo "ffmpeg is required" >&2; exit 1; }
ffmpeg -hide_banner -encoders 2>/dev/null | grep -q libvorbis || {
  echo "ffmpeg has no libvorbis encoder" >&2; exit 1; }

# Vorbis in Ogg, mono. Chromium decodes Vorbis in-process for Web Audio on every
# platform we ship to, so it needs nothing from the Android media stack — which
# Opus in Ogg would, and that is only guaranteed from API 29 while minSdk is 26.
# 32 kHz keeps the sibilance in `pspsps` (peaks near 6.5 kHz) and still halves
# the file against 44.1.
enc=(-c:a libvorbis -q:a 1 -ac 1 -ar 32000 -y)

say() { printf '  %-9s %s\n' "$1" "$2"; }

# ---------------------------------------------------------------- bell (FINAL)
#
# Chowning FM: one carrier phase-modulated by an inharmonic partial (ratio
# 1.408) with its own faster-decaying index. That inharmonicity is what makes it
# read as struck metal rather than as a sine beep, and it is why the synthesised
# version needs no apology.
say bell "FM strike, 1.8s"
ffmpeg -hide_banner -loglevel error \
  -f lavfi -i "aevalsrc='0.85*exp(-3.1*t)*sin(2*PI*784*t + 4.2*exp(-4.4*t)*sin(2*PI*1104*t))':d=1.8:s=44100" \
  -af "afade=t=in:st=0:d=0.004,alimiter=limit=0.95" \
  "${enc[@]}" "$out/bell.ogg"

# -------------------------------------------------------------- pspsps (FINAL)
#
# The cat-summoning tongue click. This one is real: /ps/ is a broadband
# sibilant, and band-passed white noise under a sharp-attack envelope IS the
# sound, not an impression of it. Three bursts, the third held longer, which is
# the natural rhythm people actually use.
say pspsps "3 sibilant bursts, 0.62s"
ffmpeg -hide_banner -loglevel error \
  -f lavfi -i "aevalsrc='(random(0)*2-1)*( between(t,0,0.09)*exp(-26*t) + between(t,0.17,0.26)*exp(-26*(t-0.17)) + between(t,0.34,0.50)*exp(-18*(t-0.34)) )':d=0.62:s=44100" \
  -af "highpass=f=2600,bandpass=f=6300:width_type=h:w=4400,volume=9dB,alimiter=limit=0.95" \
  "${enc[@]}" "$out/pspsps.ogg"

# --------------------------------------------------------- meow (PLACEHOLDER)
#
# A rise-then-fall pitch glide through two formants. Instantaneous frequency is
# 430 + 300*sin(PI*t/0.55), so the phase is the closed-form integral of that —
# aevalsrc has no state to integrate with. Reads as a small animal cry; it does
# not read as an actual cat. Replace it.
# aevalsrc has no way to name a subexpression, so the phase term is spelled out
# in full at each harmonic. It is 2*PI*(430*t + 52.52*(1-cos(PI*t/0.55))).
say meow "glide + formants, 0.75s — PLACEHOLDER"
ffmpeg -hide_banner -loglevel error \
  -f lavfi -i "aevalsrc='(sin(2*PI*(430*t + 52.52*(1-cos(PI*t/0.55))))+0.5*sin(2*2*PI*(430*t + 52.52*(1-cos(PI*t/0.55))))+0.32*sin(3*2*PI*(430*t + 52.52*(1-cos(PI*t/0.55))))+0.18*sin(4*2*PI*(430*t + 52.52*(1-cos(PI*t/0.55)))))*(min(1,t/0.03))*exp(-2.6*t)*between(t,0,0.70)':d=0.75:s=44100" \
  -filter_complex "[0:a]asplit=2[a][b];[a]bandpass=f=900:width_type=h:w=650[f1];[b]bandpass=f=2150:width_type=h:w=900,volume=-5dB[f2];[f1][f2]amix=inputs=2:normalize=0,vibrato=f=17:d=0.12,volume=8dB,alimiter=limit=0.95[o]" \
  -map "[o]" "${enc[@]}" "$out/meow.ogg"

# --------------------------------------------------------- bark (PLACEHOLDER)
#
# A pitch-collapsing buzz (340 -> 150 Hz) with a broadband transient stapled to
# the front, lowpassed to take the fizz off. The shape of a "woof" without any
# of the throat. Replace it.
say bark "buzz + transient, 0.35s — PLACEHOLDER"
ffmpeg -hide_banner -loglevel error \
  -f lavfi -i "aevalsrc='( sin(2*PI*(150*t+13.57*(1-exp(-14*t)))) + 0.7*sin(2*2*PI*(150*t+13.57*(1-exp(-14*t)))) + 0.5*sin(3*2*PI*(150*t+13.57*(1-exp(-14*t)))) + 0.3*sin(4*2*PI*(150*t+13.57*(1-exp(-14*t)))) + 0.55*(random(0)*2-1)*exp(-42*t) )*(min(1,t/0.004))*exp(-15*t)':d=0.35:s=44100" \
  -af "lowpass=f=3400,bandpass=f=700:width_type=h:w=1800,volume=10dB,alimiter=limit=0.95" \
  "${enc[@]}" "$out/bark.ogg"

# ------------------------------------------------------ goodboy (PLACEHOLDER)
#
# NOT SPEECH. There is no TTS on this machine — espeak-ng is absent and the only
# libespeak-ng reference left behind is a dangling speech-dispatcher module — so
# this is two voice-shaped syllables carrying the falling-then-falling prosody of
# "good boy". It stands in for a real recording; it does not say anything.
say goodboy "2 voiced syllables, 0.72s — PLACEHOLDER, NOT SPEECH"
ffmpeg -hide_banner -loglevel error \
  -f lavfi -i "aevalsrc='( (sin(2*PI*(168*t-30*t*t))+0.6*sin(2*2*PI*(168*t-30*t*t))+0.35*sin(3*2*PI*(168*t-30*t*t)))*between(t,0,0.24)*(min(1,t/0.02))*exp(-4.5*t) + (sin(2*PI*(176*(t-0.30)-52*(t-0.30)*(t-0.30)))+0.6*sin(2*2*PI*(176*(t-0.30)-52*(t-0.30)*(t-0.30)))+0.35*sin(3*2*PI*(176*(t-0.30)-52*(t-0.30)*(t-0.30))))*between(t,0.30,0.70)*(min(1,(t-0.30)/0.02))*exp(-3.2*(t-0.30)) )':d=0.72:s=44100" \
  -filter_complex "[0:a]asplit=2[a][b];[a]bandpass=f=640:width_type=h:w=500[f1];[b]bandpass=f=1080:width_type=h:w=700,volume=-4dB[f2];[f1][f2]amix=inputs=2:normalize=0,lowpass=f=3000,volume=11dB,alimiter=limit=0.95[o]" \
  -map "[o]" "${enc[@]}" "$out/goodboy.ogg"

echo
ls -l "$out"/*.ogg | awk '{printf "  %-42s %6.1f KB\n", $NF, $5/1024}'
